server.port=8080

spring.datasource.url=jdbc:oracle:thin:@${ORACLE_TNS_ALIAS:inscripcionesdb_high}?TNS_ADMIN=${ORACLE_WALLET_PATH:/app/oracle-wallet}
spring.datasource.username=${ORACLE_DB_USER:INSCRIPCIONES_USER}
spring.datasource.password=${ORACLE_DB_PASSWORD:}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true

azure.b2c.tenant-id=4ba371a5-2d60-4c43-bc38-a63974911ffb
azure.b2c.client-id=cd54f9ac-4fed-48bc-921c-6014aab02776
azure.b2c.client-secret=${AZURE_CLIENT_SECRET}
azure.b2c.tenant-name=DuocAzurexAlonso
azure.b2c.user-flow=B2C_1_signupsignin

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://DuocAzurexAlonso.b2clogin.com/DuocAzurexAlonso.onmicrosoft.com/B2C_1_signupsignin/discovery/v2.0/keys
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://DuocAzurexAlonso.b2clogin.com/4ba371a5-2d60-4c43-bc38-a63974911ffb/v2.0/

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

aws.s3.bucket-name=${AWS_S3_BUCKET:inscripciones-resumenes}
aws.s3.region=${AWS_REGION:us-east-2}
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}

management.endpoints.web.exposure.include=health
